name: deploy-game
run-name: ${{ github.actor }} is deploying WizGame
on: [push]
jobs:
  deploy-build-game:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        # Get correct Target
        - run: rustup target add wasm32-unknown-unknown
        # Build
        - run: bash build_wasm_linux.sh
        # Zip
        - run: zip -r wbindgen.zip wbindgen
        # Deploy
        - uses: manleydev/butler-publish-itchio-action@master
          env:
            BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
            CHANNEL: html5
            ITCH_GAME: wiz-game
            ITCH_USER: Ianplatt
            PACKAGE: wbindgen.zip